comment = "// "
language_server.command = "rust-analyzer"
language_server.args = ["-v", "--log-file", "/tmp/rust-analyzer.log"]

[[snippet]]
trigger="li"
body="log::info!($0)"

[[snippet]]
trigger="fn"
body="""\
fn ${3:name}($2) -> ${1:()}{
    \t$0
}\
"""
