[colors.window]
default = "#1D1F21,#c1c1c1,"
statusline = "#404040,#bbbbbb,"
statusline_no_focus = "#0d0d0d,#bbbbbb,"
end_of_buffer = ",#666666,"
trailing_whitespace = ",#666666,"
symbols = ",#444444,"
match = "#B5BD68,#222222,"
virtual = ",#666666,"

[colors.cursor]
normal = "#d7875f,#000000,"
selection = "#3a3f41,#d3d3d3,"

[colors.window.view]
hint = "#7AA6DA,#222222,"
info = "#7AA6DA,#222222,"
warn = "#F8C75B,#222222,"
error = "#E97866,#222222,"

constant = ",#7AA6DA,"
string =  ",#7AA6DA,"

keyword = ",#d7875f,"
operator =  ",#83a4af,"
type =  ",#d7af5f,"
comment = ",#B5BD68,"
preproc = ",#B294BB,"
special = ",#B294BB,"
identifier = ",#d7875f,"

[colors.window.completion]
default = "#303030,#d1caca,"
description = ",#777777,"
match = ",#d7875f,"

[colors.window.completion.selected]
default = "#4a4a4a,,"
description = ",#777777,"
match = ",#d7875f,"

[colors.prompt]
default = "#758F75,#000000,"
message = ",,bold"
userinput = ",,"

[colors.prompt.overlay]
default = "#303030,#d1caca,"
title = ",,bold"
message = ",#d1caca,bold"

[colors.prompt.completion]
default = "#303030,#c1baba,"
description = ",#777777,"
match = ",#d7875f,"

[colors.prompt.completion.selected]
default = "#4a4a4a,,"
description = ",#777777,"
match = ",#d7875f,"

[colors.filetree]
default = "#1D1F21,#c1c1c1,"
markers = ",#B5BD68,"
directory = ",#d7875f,"

[colors.filetree.selected]
default = "#353535,,"
directory = ",#d7875f,"
markers = ",#B5BD68,"

[colors.locations]
default = "#1D1F21,#c1c1c1,"
title = "#353535,#b1aaaa,"
entry = ""
group = ",#7AA6DA,"
markers = ",#B5BD68,"
match = ",#d7875f,"

[colors.locations.selected]
default = "#353535,,"
match = ",#d7875f,"
markers = ",#B5BD68,"
entry = ""
group = ",#7AA6DA,"

[colors.popup]
default = "#303030,#d1caca,"
