# DARK RED FG #7e0c1d

[colors.window]
default = "#E2DBC8,#202020,"
statusline = "#B8A282,#2a130d,"
statusline_no_focus = "#B8B4A9,#2a130d,"
end_of_buffer = ",#7f755f,"
trailing_whitespace = ",#7f755f,"
match = "#99bad1,,"
virtual = ",#7f755f,"

[colors.cursor]
normal = "#86beaf,,"
selection = "#d8c8a9,,"
primary = "#C0A886,,"

[colors.window.view]
hint = "#99bad1,#000020,"
info = "#99bad1,#000020,"
warn = "#fde37c,#413403,"
error = "#da7073,#000000,"

constant = ",#014CC0,"
string =  ",#014CC0,"

keyword = ",#a84d1f,"
type =  ",#824b26,"
operator =  ",#456882,"
comment = ",#006200,"
preproc = ",#432378,"
special = ",#432378,"
identifier = ",#824b26,"

[colors.window.completion]
default = "#d8c8a9,#2a130d,"
description = ",#6f654f,"
match = ",#b0463a,"

[colors.window.completion.selected]
default = "#efb679,,"
description = ",#5a433d,"
match = ",#b0463a,"

[colors.prompt]
default = "#76aa76,#000000,"
message = ",,bold"
userinput = ",#000000,"

[colors.prompt.overlay]
default = "#d8ccb4,#000000,"
title = ",#1d1d1d,bold"
message = ",,bold"
userinput = ",,"

[colors.prompt.completion]
default = "#d8ccb4,#000000,"
description = ",#7f755f,"
match = ",#b0463a,"

[colors.prompt.completion.selected]
default = "#efb679,,"
description = ",#5a433d,"
match = ",#b0463a,"

[colors.filetree]
default = "#E2DBC8,#000000,"
# file = ""
directory = ",#824b26,"
markers = ",#355d8d,"

[colors.filetree.selected]
default = "#d8c8a9,,"
# file = ""
directory = ",#824b26,"
markers = ",#355d8d,"

[colors.locations]
default = "#E2DBC8,#000000,"
title = "#B8A282,#2a130d,"
entry = ""
group = ",#824b26,"
markers = ",#355d8d,"
match = ",#b0463a,"

[colors.locations.selected]
default = "#d0bd97,,"
match = ",#b0463a,"
markers = ",#355d8d,"

[colors.popup]
default = "#d8ccb4,#000000,"
