# DARK RED FG #7e0c1d

[colors.window]
default = "#E2DBC8,#202020,"
statusline = "#B8A282,#2a130d,"
gutter = ",#4C4C4C,bold"
end_of_buffer = ",#7f755f,"
trailing_whitespace = ",#7f755f,"
symbols = ",#606060,"
match = "#C0A886,,"

[colors.window.cursor]
default = "#a4ac86,,"
# selection = "#efb679,,"
selection = "#d0bd97,,"
primary = "#C0A886,,"

[colors.window.view]
# hint = "#00917e,#000000,"
hint = "#d5cce3,#3856d1,"
info = "#e5dcf3,#3856d1,"
# guifg=#3856d1 guibg=#e5dcf3
warn = "#fde37c,#615413,"
# guifg=#615413 guibg=#fde37c
error = "#f2d8d8,#b22e32,"
# =#b22e32 guibg=#f2d8d8


constant = ",#014CC0,"
string =  ",#014CC0,"
number = ",#014CC0,"

keyword = ",#a84d1f,"
type =  ",#824b26,"
operator =  ",#008080,"
comment = ",#006200,"
preproc = ",#432378,"

identifier = ",#824b26,"

[colors.window.completion]
default = "#B8A282,#2a130d,"
description = ",#6f654f,"
match = ",#b0463a,"

[colors.window.completion.selected]
default = "#efb679,,"
description = ",#5a433d,"
match = ",#b0463a,"

[colors.prompt]
default = "#B8A282,#000000,"
message = ",,bold"
userinput = ",#000000,"

[colors.prompt.overlay]
default = ",#000000,"
title = ",#1d1d1d,bold"
message = ",,bold"
userinput = ""

[colors.prompt.completion]
default = "#d8ccb4,#000000,"
description = ",#7f755f,"
match = ",#b0463a,"

[colors.prompt.completion.selected]
default = "#efb679,,"
description = ",#5a433d,"
match = ",#b0463a,"

[colors.filetree]
default = "#E2DBC8,#000000,"
markers = ",#355d8d,"

[colors.filetree.file]
default = ""
selected = "#c2c2c2,,"

[colors.filetree.directory]
default = ",#824b26,"
selected = "#c2c2c2,,"

[colors.locations]
default = "#E2DBC8,#000000,"
title = "#B8A282,#2a130d,"
entry = ""
group = ",#824b26,"
markers = ",#355d8d,"
match = ",#b0463a,"

[colors.locations.selected]
default = "#d0bd97,,"
match = ",#b0463a,"
markers = ",#355d8d,"

[colors.popup]
default = "#d8ccb4,#000000,"
