[colors.window]
default = "#DADADA,#3A3A3A,"
statusline = "#b5b5b5,#000000,"
statusline_no_focus = "#DADADA,#000000,"
end_of_buffer = ",#4E4E4E,"
trailing_whitespace = ",#7f755f,"
symbols = ",#606060,"
match = "#8FB88F,,"
virtual = ",#999999,"

[colors.cursor]
default = "#8FB7DE,,"
selection = "#c2c2c2,,"
primary = "#5F87AE,,"

[colors.window.view]
hint = "#B4CBF0,#014CB0,"
info = "#B4CBF0,#014CB0,"
warn = "#ffe699,#514403,"
error = "#BF7E7E,#392525,"

constant = ",#274172,"
string =  ",#0750b1,"
keyword = ",#005F00,"
type =  ",#824116,"
operator =  ",#007f58,"
comment = ",#777777,"
preproc = ",#533388,"
special = ",#533388,"
identifier = ",#824116,"

[colors.window.completion]
default = "#E8E8E8,#3A3A3A,"
description = ",#909090,"
match = ",,"

[colors.window.completion.selected]
default = "#CACACA,,"
description = ",#808080,"
match = ",,"

[colors.prompt]

default = "#7fa87f,#000000,"
message = ",,"
userinput = ",#000000,"

[colors.prompt.overlay]
default = ",,"
title = ",,"
message = ",,"
userinput = ""

[colors.prompt.completion]
default = "#E8E8E8,#3A3A3A,"
description = ",#7f755f,"
match = ",#b0463a,"

[colors.prompt.completion.selected]
default = "#CACACA,,"
description = ",#5a433d,"
match = ",#b0463a,"

[colors.filetree]
default = "#DADADA,#3A3A3A,"
markers = ",#014CC0,"
# file = ""
directory = ",#824116,"

[colors.filetree.selected]
default = "#c2c2c2,,"
# file = ""
directory = ",#824116,"
markers = ",#014CC0,"

[colors.locations]
default = "#DADADA,#3A3A3A,"
title = "#b5b5b5,#202020,"
entry = ""
group = ",#824116,"
markers = ",#355d8d,"
match = ",#b0463a,"

[colors.locations.selected]
default = "#c2c2c2,,"
match = ",#b0463a,"
markers = ",#355d8d,"

[colors.popup]
default = "#E8E8E8,#4A4A4A,"
hint = ",#014CC0,"
info = ",#014CC0,"
warn = ",#a56d00,"
error = ",#870100,"
