[colors.window]
default = "#DADADA,#3A3A3A,"
statusline = "#5F885F,#000000,"
statusline_no_focus = "#888888,#000000,"
gutter = ",#4C4C4C,bold"
end_of_buffer = ",#4E4E4E,"
trailing_whitespace = ",#7f755f,"
symbols = ",#606060,"
match = "#8FB88F,,"
virtual = ",#999999,"

[colors.window.cursor]
default = "#8FB7DE,,"
selection = "#c2c2c2,,"
primary = "#5F87AE,,"

[colors.window.view]
hint = "#8EACD0,#1D232B,"
info = "#8EACD0,#1D232B,"
warn = "#ffe699,#514403,"
error = "#BF7E7E,#392525,"

constant = ",#014CC0,"
string =  ",#216CD0,"
number = ",#014CC0,"

keyword = ",#005F00,"
type =  ",#824b26,"
operator =  ",#008787,"
comment = ",#870100,"
preproc = ",#533388,"

identifier = ",#824b26,"

[colors.window.completion]
default = "#E8E8E8,#3A3A3A,"
description = ",#909090,"
match = ",,"

[colors.window.completion.selected]
default = "#CACACA,,"
description = ",#808080,"
match = ",,"

[colors.prompt]
default = "#5F885F,#000000,"
message = ",,"
userinput = ",#000000,"

[colors.prompt.overlay]
default = ",,"
title = ",,"
message = ",,"
userinput = ""

[colors.prompt.completion]
default = "#E8E8E8,#3A3A3A,"
description = ",#7f755f,"
match = ",#b0463a,"

[colors.prompt.completion.selected]
default = "#CACACA,,"
description = ",#5a433d,"
match = ",#b0463a,"

[colors.filetree]
default = "#DADADA,#3A3A3A,"
markers = ",#014CC0,"

[colors.filetree.file]
default = ""
selected = "#c2c2c2,,"

[colors.filetree.directory]
default = ",#824b26,"
selected = "#c2c2c2,,"

[colors.locations]
default = "#DADADA,#3A3A3A,"
title = "#5F885F,#202020,"
entry = ""
group = ",#824b26,"
markers = ",#355d8d,"
match = ",#b0463a,"

[colors.locations.selected]
default = "#c2c2c2,,"
match = ",#b0463a,"
markers = ",#355d8d,"

[colors.popup]
default = "#E8E8E8,#4A4A4A,"
hint = ",#014CC0,"
info = ",#014CC0,"
warn = ",#a56d00,"
error = ",#870100,"
