# TODO ignore whitespace with options?

WHITESPACE: [ \t\r\n];

value:  object / array / number / string / true / false / null;
object: "{" member ("," member)* "}";
member: string ":" value;

array: "[" value ("," value )* "]";

number: "-"? integer ("." [0..9]+)?;
string: quote ([\x20..\x21] / [\x23..\x5b] / [\x5d..\x10ffff])* quote;
true: "true";
false: "false";
integer: "0" / [1..9] [0..9]*;
quote: "\"";
