# TODO ignore whitespace with options?

value: _ (Object / Array / Number / String / True / False / Null) _;
Object: "{" _ Member (_ "," _ Member)* _ "}";
Member: String _ ":" Value;

Array: "[" _ Value  (_ "," _ Value )* _ "]";

Number: "-"? Integer ("." [0..9]+)?;
String: Quote ([\x20..\x21] / [\x23..\x5b] / [\x5d..\x10ffff])* Quote;
True: "true";
False: "false";
integer: "0" / [1..9] [0..9]*;
quote: "\"";

_: [ \t\r\n]*;
