[colors.window]
default = "#1D1F21,#c1c1c1,"
statusline = "#353535,#b1aaaa,"
gutter = ",#4C4C4C,bold"
end_of_buffer = ",#555555,"
trailing_whitespace = ",#666666,"
symbols = ",#444444,"
match = "#B5BD68,#222222,"

[colors.window.cursor]
default = "#d7875f,#000000,"
selection = "#81A2BE,#222222,"
primary = "#81A2BE,#222222,"

[colors.window.view]
hint = "#33334a,#66bbe9,"
info = "#33334a,#66bbe9,"
warn = "#3F3B31,#F8C75B,"
error = "#3E3332,#E97866,"

constant = ",#7AA6DA,"
string =  ",#7AA6DA,"
number = ",#7AA6DA,"

keyword = ",#d7875f,"
operator =  ",#8ABEB7,"
type =  ",#d7af5f,"
comment = ",#B5BD68,"
preproc = ",#B294BB,"

identifier = ",#d7875f,"

[colors.window.completion]
default = "#303030,#d1caca,"
description = ",#777777,"
match = ",#d7875f,"

[colors.window.completion.selected]
default = "#4a4a4a,,"
description = ",#777777,"
match = ",#d7875f,"

[colors.prompt]
default = "#303030,#d1caca,"
message = ",,bold"
userinput = ",,"

[colors.prompt.overlay]
default = ",#d1caca,"
title = ",,bold"
message = ",#d1caca,bold"

[colors.prompt.completion]
default = "#303030,#c1baba,"
description = ",#777777,"
match = ",#d7875f,"

[colors.prompt.completion.selected]
default = "#4a4a4a,,"
description = ",#777777,"
match = ",#d7875f,"

[colors.filetree]
default = "#1D1F21,#c1c1c1,"
file = ""
directory = ",#d7875f,"
markers = ",#B5BD68,"

[colors.filetree.selected]
default = "#404040,,"
file = ""
directory = ",#d7875f,"

[colors.locations]
default = "#1D1F21,#c1c1c1,"
title = "#353535,#b1aaaa,"
entry = ""
group = ",#7AA6DA,"
markers = ",#B5BD68,"
match = ",#d7875f,"

[colors.locations.selected]
default = "#404040,,"
match = ",#d7875f,"
markers = ",#B5BD68,"
entry = ""
group = ",#7AA6DA,"

[colors.popup]
default = "#303030,#d1caca,"
