[colors.window]
default = "#1D1F21,#c1c1c1,"
statusline = "#303030,#b1aaaa,"
gutter = ",#4C4C4C,bold"
end_of_buffer = ",#7f755f,"
trailing_whitespace = ",#7f755f,"
symbols = ",#606060,"
match = "#C0A886,,"

[colors.window.cursor]
default = "#a4ac86,,"
# selection = "#efb679,,"
selection = "#d0bd97,,"
primary = "#C0A886,,"

[colors.window.view]
info = "#00917e,#000000,"
warn = "#ff8c5a,#000000,"
error = "#c0564a,#ffffff,"

string =  ",#d7af5f,"
identifier = ",#D7875F,"
constant = ",#5fafd7,"
number = ",#5fafd7,"
keyword = ",#d7875f,"
operator =  ",#a84d1f,"
type =  ",#d7af5f,"
comment = ",#5faf5f,"
preproc = ",#ff8700,"
# BLUE #5fafd7

[colors.window.completion]
default = "#B8A282,#2a130d,"
description = ",#6f654f,"
match = ",#ff8700,"

[colors.window.completion.selected]
default = "#efb679,,"
description = ",#5a433d,"
match = ",#ff8700,"

[colors.prompt]
default = "#303030,#d1caca,"
message = ",,bold"
userinput = ",#a8a8a8,"

[colors.prompt.overlay]
default = ",#d1caca,"
title = ",,bold"
message = ",#d1caca,bold"

[colors.prompt.completion]
default = "#303030,#c1baba,"
description = ",#777777,"
match = ",#d7875f,"

[colors.prompt.completion.selected]
default = "#404040,,"
description = ",#777777,"
match = ",#d7875f,"

[colors.filetree]
default = "#E2DBC8,#000000,"
file = ""
directory = ",#824b26,"
markers = ",#355d8d,"
# selected = "#efb679,,"
selected = "#d0bd97,,"

[colors.locations]
default = "#E2DBC8,#000000,"
title = "#B8A282,#2a130d,"
entry = ""
group = ",#824b26,"
markers = ",#355d8d,"
match = ",#b0463a,"

[colors.locations.selected]
default = "#d0bd97,,"
match = ",#b0463a,"
markers = ",#355d8d,"

[colors.popup]
default = "#d8ccb4,#000000,"
