# DARK RED FG #7e0c1d

[colors.window]
default = "#E2DBC8,#000000,"
statusline = "#B8A282,#2a130d,"
gutter = ",#4C4C4C,bold"
end_of_buffer = ",#7f755f,"
symbols = ",#606060,"
match = "#C0A886,,"

[colors.window.cursor]
default = "#a4ac86,,"
selection = "#efb679,,"
primary = "#C0A886,,"

[colors.window.view]
info = "#00917e,#000000,"
warn = "#ff8c5a,#000000,"
error = "#c0564a,#000000,"

string =  ",#3C780A,"
constant = ",#4f3693,"
identifier = ",#824b26,"
number = ",#452F81,"
comment = ",#355d8d,"
operator =  ",#a84d1f,"
type =  ",#824b26,"
keyword = ",#014CC0,"
preproc = ",#014CC0,"

[colors.window.completion]
default = "#B8A282,#2a130d,"
description = ",#6f654f,"
match = ",#b0463a,"

[colors.window.completion.selected]
default = "#efb679,,"
description = ",#5a433d,"
match = ",#b0463a,"


[colors.prompt]
default = "#B8A282,#000000,"
message = ",,bold"
userinput = ",#000000,"

[colors.prompt.overlay]
default = ",#000000,"
title = ",#1d1d1d,bold"
message = ",,bold"
userinput = ""

[colors.prompt.completion]
default = "#d8ccb4,#000000,"
description = ",#7f755f,"
match = ",#b0463a,"

[colors.prompt.completion.selected]
default = "#efb679,,"
description = ",#5a433d,"
match = ",#b0463a,"

[colors.filetree]
default = "#d8ccb4,#000000,"
file = ""
directory = ",#824b26,"
markers = ",#355d8d,"
selected = "#efb679,,"

[colors.locations]
default = "#d8ccb4,#000000,"
entry = ""
group = ",#824b26,"
markers = ",#355d8d,"
match = ",#b0463a,"

[colors.locations.selected]
default = "#efb679,,"
match = ",#b0463a,"
