[package]
name = "sanedit-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "sane"
path = "src/main.rs"

[dependencies]
sanedit-terminal-client = { path = "../terminal-client" }
sanedit-editor = { path = "../editor" }
sanedit-server = { path = "../server" }

clap = { workspace = true, features = ["derive"] }
log.workspace = true
log4rs.workspace = true
