document = (title / list_op / link / backtick / (!WHITESPACE .) WHITESPACE / .)*;

WHITESPACE = [ \t];
ws = WHITESPACE*;
nl = "\r\n" / "\n";

@show @whitespaced @highlight(identifier)
title = "#"+ (!nl .)*;

@show @highlight(operator)
list_op = nl ws "*" / "-" / "+";

link = "[" link_name "](" link_url ")";
@show @highlight(keyword)
link_name = (!"]" .)*;

@show @highlight(constant)
link_url = (!")" .)*;

@show @highlight(operator)
backtick = "`" (!"`" .)* "`";
