document = element !.;

element = (recursive_wildcard / (wildcard / any / brackets / negative_brackets / text)+) (separator element)?;

@show
separator = "/";

@show
text = [^/\[?*]+;

@show
char = [^\]];
@show
brackets = "[" "]"? bracket_inner "]";
@show
negative_brackets = "[!" "]"? bracket_inner "]";

@show
range = char "-" char;
bracket_inner = (range / char)*;

@show
any = "?";

@show
wildcard = "*";

@show
recursive_wildcard = "**";
