document = regex*;
regex = alt / sequence;

@show
alt = sequence ("|" sequence)+;

@show
sequence = (repetition / group / char / escaped_char / any)+;

@show
char = [^\[\]\.+*?\^$(){}|\\];

escaped_char = "\\" escaped;

@show
escaped = .;

@show
any = ".";

repetition = zero_or_more / one_or_more / optional;

@show
zero_or_more = (group / char / any) "*";

@show
one_or_more = (group / char / any) "+";

@show
optional = (group / char / any) "?";

@show
group = "(" regex ")";