[package]
name = "sanedit-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sane"
path = "src/main.rs"

[dependencies]
sanedit-terminal-client = { path = "../terminal-client" }
sanedit-editor = { path = "../editor" }

clap = { version = "^4", features = ["derive"] }
