#!/bin/bash
# Regexp for grep to only choose some file extensions for formatting
exts="\.\(rs\)$"
files=`git diff --cached --name-only --diff-filter=ACMR | grep $exts`

task format

# Format staged files
for file in files
do
  # echo "Formatting $file"
  # Get the file from index
  # git show ":$file" > "$file.tmp"
  # Format it
  # "$formatter" -i "$file.tmp"
  # Create a blob object from the formatted file
  hash=`git hash-object -w "$file"`
  # Add it back to index
  git update-index --add --cacheinfo 100644 "$hash" "$file"
  # Remove the tmp file
  # rm "$file.tmp"
done

# If no files left in index after formatting - fail
ret=0
if [ ! "`git diff --cached --name-only`" ]; then
  1>&2 echo "No files left after formatting"
  exit 1
fi
