[package]
name = "sanedit-editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sanedit-messages = { path = "../messages" }
sanedit-buffer = { path = "../buffer" }
sanedit-regex = { path = "../regex" }
sanedit-macros = { path = "../macros" }

# General
log         = "0.4"
parking_lot = "0.12.0"
dirs        = "4.0.0"  # Used to get easy access to different directories, tmp, config etc.

# Good helper macros for enums
strum        = "0.23"
strum_macros = "0.23"

# Error handling
anyhow      = "1.0"
thiserror   = "1.0"

# Used to store elements and generate an id for them
slotmap = "1.0"

tokio = { version = "1.20", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
futures = "0.3"

# For cells
smallvec = "0.1"
unicode-width = "0.1"
unicode-segmentation = "1.9"
